# Generated by Django 4.0.5 on 2022-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
