# Generated by Django 4.0.5 on 2022-07-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_site_is_active_sitestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestatus',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitestatus',
            name='last_check',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
